### ISSUE TITLE
TODO: Graph Search Enhancements

### ISSUE THREAD

**Issue by rsimon** [rsimon/immarkus#94]
Note to self: list of issues mentioned in email feedback:

- [x] Keep filter state when a new (incomplete) filter condition is appended
- [x] Enhance selection accuracy (currently, the node "size" is dependent on zoom level)
- [x] Issue: long property lists in the dropdown. Add a search/filter box at the top of the dropdown
- [x] When filtered, hovering over a node (image node?) should highlight connected entity classes (or all nodes?)
